import psutil  # type: ignore
import os
import time
import schedule
import sys
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders


def SendEmail(folderName, fileAttachment, emailId):
    sender_email = "nanekarshailendra@gmail.com"
    receiver_email = emailId
    password = "qiuj qygu crwu irub"
    subject = "Process Info File Log"
    body = "Hi, please find the attached Log file." \
    "\nThis log file contains the information of all running processes on the system." \
    "\nIt includes details such as PID, process name, username, and memory usage in MB." \
    "\nThis log is generated by the Marvellous Infosystem Process Logger script." \
    "\n\nThank you for using our service!"
    

    msg = MIMEMultipart()
    msg["From"] = sender_email
    msg["To"] = receiver_email
    msg["Subject"] = subject
    msg.attach(MIMEText(body, "plain", "utf-8"))
    logfilepath = os.path.join(folderName, fileAttachment)
    attachment = open(logfilepath, "rb")
    part = MIMEBase("application", "octet-stream")
    part.set_payload(attachment.read())
    encoders.encode_base64(part)

    part.add_header(
        "Content-Disposition", 'attachment; filename= "%s"' % fileAttachment
    )
    msg.attach(part)
    try:
        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login(sender_email, password)
        server.send_message(msg)
        server.quit()
        print("Email sent successfully!")
    except Exception as e:
        print(f"Failed to send email: {e}")


def CreateLog(FolderName, emailId):
    flag1 = os.path.exists(FolderName)
    if flag1 == False:
        os.mkdir(FolderName)

    timestamp = time.ctime()

    filename = "MarvellousLog%s.log" % (timestamp)
    filename = filename.replace(" ", "_")
    filename = filename.replace(":", "_")
    logfileName = os.path.join(FolderName, filename)
    flag2 = os.path.exists(logfileName)
    if flag2 == False:
        logfile = open(logfileName, "w")
        logfile.close()
    logfile = open(logfileName, "a")
    Border = "-" * 50
    logfile.write(Border)
    logfile.write("\nMarvellous Infosystem Process Log\n")
    logfile.write("Log file is created at : " + time.ctime() + "\n")
    logfile.write(Border + "\n")

    Data = ProcessScan()
    for content in Data:
        logfile.write("%s \n" % content)
    logfile.close()

    SendEmail(FolderName, filename, emailId)


def ProcessScan():

    listProcess = []

    for proc in psutil.process_iter():
        try:

            info = proc.as_dict(attrs=["pid", "name", "username"])
            info["vms"] = proc.memory_info().vms / (1024 * 1024)
            listProcess.append(info)
        except (psutil.AccessDenied, psutil.ZombieProcess, psutil.NoSuchProcess):
            pass

    return listProcess


def main():
    CreateLog(sys.argv[1], sys.argv[2])


if __name__ == "__main__":
    main()
